### ISSUE TITLE
Login credentials

### ISSUE THREAD

**Issue by hamza-gaya** [4jean/lav_sms#10]
Could you please provide login credentials of admin and super admin ??

**Comment by AFNANAMIN** [comment]
yes i am also unable to login into any account

**Comment by mrsaleem92** [comment]
go to login blade and change  input name from identity to email it will work

**Comment by godilite** [comment]
This plus other issues are fixed in this PR https://github.com/4jean/lav_sms/pull/13#issue-493696564

**Comment by 4jean** [comment]
Please Check fix Line 43
https://github.com/4jean/lav_sms/blob/master/app/Http/Controllers/Auth/LoginController.php

**Comment by 4jean** [comment]
Please Check fix..Oveeride username method of trait _AuthenticatesUsers_

https://github.com/4jean/lav_sms/blob/master/app/Http/Controllers/Auth/LoginController.php

```
public function username () 
    {
        $identity = request()->identity;
        $field = filter_var($identity, FILTER_VALIDATE_EMAIL) ? 'email' : 'username';
        request()->merge([$field => $identity]);
        return $field;
    }
```

**Comment by mt4real** [comment]
Unable to change username and name
