### ISSUE TITLE
login credentials

### ISSUE THREAD

**Issue by AFNANAMIN** [4jean/lav_sms#11]
could you plz let you know the valid credentials i am  unable to login as user or admin

**Comment by hafizghk** [comment]
have you try the password "cj"?

**Comment by 4jean** [comment]
In https://github.com/4jean/lav_sms/blob/master/database/seeds/UsersTableSeeder.php the password is clearly written line 30 and 31. Please seed database with php artisan:db seed after migrating database

**Comment by godilite** [comment]
this issue is fixed with this PR [](https://github.com/4jean/lav_sms/pull/13#issue-493696564) @4jean please review and merge if suitable

**Comment by 4jean** [comment]
Thanks @godilite. I wanted to include Username/Email Login. Issue fixed
