### ISSUE TITLE
User username

### ISSUE THREAD

**Issue by seesimon** [4jean/lav_sms#15]
Hi just want a help in modify little in this coding .. whenever i save a new user especially for accounant,teacher and parents username .. its not displaying the original username i enterd .. unless its showing like qs/staff/1970/5708 .. may i know how to change it ......
and why there is no account for create librarian and student

**Comment by 4jean** [comment]
- You can create Students when you click the students tab. You can click **Admit Student** to create new student. 
- There's no librarian feature added yet. I'm still working on the librarian user and will update the repo later. 
- You can modify the username/user code during user creation at **store** method of https://github.com/4jean/lav_sms/blob/master/app/Http/Controllers/SupportTeam/UserController.php Other staffs have staff-code except (Super Admins & Admins - teamSA) Line 81
You can modify student's username at **store** method of https://github.com/4jean/lav_sms/blob/master/app/Http/Controllers/SupportTeam/StudentRecordController.php Line 66
