### ISSUE TITLE
/timetables route error

### ISSUE THREAD

**Issue by naghiloo** [4jean/lav_sms#17]
This causes/timetables route error when the application is running. Because there are some syntax errors in using models in the **TimeTableRepo.php** file. the first character of the model should be capital. 

Solution:
App\models\TimeSlot --> App\\**Models**\TimeSlot
App\models\TimeTable --> App\\**Models**\TimeTable
App\models\TimeTableRecord --> App\\**Models**\TimeTableRecord.

**Comment by 4jean** [comment]
Thanks a lot for your comment. This issue is now resolved
