### ISSUE TITLE
User image and school logo

### ISSUE THREAD

**Issue by TANNKOANO** [4jean/lav_sms#19]
Hi 4Jean,
Thanks for this amazing work.
I noticed that the path of image seems to not work.
when i change the user image it doesn't show.
the path is http://localhost:8000/storage/uploads/super_admin/DV8VSGPUT7/photo.png but in the folders they are located to 
http://localhost:8000/storage/_**app/public**_/uploads/super_admin/DV8VSGPUT7/photo.png.
any tip to solving this?
Thanks

**Comment by ljoboy** [comment]
just run `php artisan link:storage`

**Comment by 4jean** [comment]
The files are stored in the public disk, so you can use `php artisan storage:link `more info at https://laravel.com/docs/8.x/filesystem#the-public-disk

**Comment by TANNKOANO** [comment]
Thanks you @4jean .
