### ISSUE TITLE
About some commands that are not included in the program code

### ISSUE THREAD

**Issue by 06fitreeyru** [4jean/lav_sms#23]
Why can't admin create student account? Students can't see teacher profiles, class schedules, etc., can only Marksheet

**Comment by 4jean** [comment]
- Super Admins & Admins can create Student Accounts (Login as Admin > click Students > Click Admit Student).
- Students can only see their profiles
- Students/Teachers can only see schedules/timetables when it has been created by Admin/Super Admin. (Login as Admin/Super Admin) > Click Academics > Click Timetables.

**_Please note that the default features of this app, may not meet everyone's need, so you're free to [clone the repo](https://github.com/4jean/lav_sms.git) and modify **
