### ISSUE TITLE
Missing Class

### ISSUE THREAD

**Issue by AllanMwaura22** [4jean/lav_sms#27]
Target class [App\Http\Requests\TimeTable\TTRecordRequest] does not exist 
On Timetables

**Comment by yungifez** [comment]
Please can you post a screenshot of your code and the error

**Comment by AllanMwaura22** [comment]
![tt_error1](https://user-images.githubusercontent.com/42067875/128543012-325ec199-df5a-4594-9997-980e88d57388.png)
![tt_error2](https://user-images.githubusercontent.com/42067875/128543060-7d9ef5a3-6aaf-431e-b59f-b5755941ff8f.png)

**Comment by yungifez** [comment]
Lol I got this error yesterday too

So the class does not follow psr aytoloading standards 

No worries cause it's a simple fix

Just change the folder name Timetables at app/http/requests to TimeTable

**Comment by 4jean** [comment]
THanks @yungifez for the quick-fix

**Comment by yungifez** [comment]
You are welcome sir 

Nice project

Once messaged you on whatsapp 

Once I learn the workings of git, I'll try my best to contribute

Maybe a notice board or something

**Comment by 4jean** [comment]
> You are welcome sir
> 
> Nice project
> 
> Once messaged you on whatsapp
> 
> Once I learn the workings of git, I'll try my best to contribute
> 
> Maybe a notice board or something

no problem @yungifez
