### ISSUE TITLE
Trying to get property 'description' of non-object (View: C:\xampp\htdocs\lav_sms\resources\views\partials\login\header.blade.php)

### ISSUE THREAD

**Issue by dawsonlobo** [4jean/lav_sms#33]
I have locally deployed the server. But I am getting this error. Kindly help me out

**Comment by dawsonlobo** [comment]
Thank you. Problem is resolved

**Comment by yungifez** [comment]
> 

Can you post maybe a screenshot

**Comment by shourov-sorkar** [comment]
> Thank you. Problem is resolved

Can you please share how can you solve this problem?

**Comment by yungifez** [comment]
Do you have an error?

**Comment by yungifez** [comment]
If its the above error, try seeding the database 

Run php artisan db:seed
