### ISSUE TITLE
Unable to update user, parents or teacher photo

### ISSUE THREAD

**Issue by sachinraj07** [4jean/lav_sms#37]
When creating a parent, the image is successfully uploaded but after creating unable to update the photo. 
This error comes - 500 Internal Server Error Please Check for Duplicate entry or Contact School Administrator/IT Personnel

**Comment by sachinraj07** [comment]
Please solve this error, already try 2 hours

**Comment by 4jean** [comment]
sorry about the ussue fixed in 8f8d922e30cb0f1e0fe6e1a01dff054c3544b785
