### ISSUE TITLE
Marksheet does not show in teacher, parents and students user.

### ISSUE THREAD

**Issue by sachinraj07** [4jean/lav_sms#39]

**Comment by yungifez** [comment]
Can you elaborate more on your issue

**Comment by sachinraj07** [comment]
when i add marks of a student of an exam as a super admin, marksheet of student shows when login as a super admin. But marksheets does not show when login as that student, their parent or a teacher as a user.

**Comment by sachinraj07** [comment]
where to check?

**Comment by yungifez** [comment]
Check the settings and maybe post a screenshot

**Comment by sachinraj07** [comment]
in setting Lock Exam is No selected

**Comment by yungifez** [comment]
Post a screenshot of your issue 

Maybe I'll understand more

**Comment by sachinraj07** [comment]
ok wait

**Comment by sachinraj07** [comment]
![student](https://user-images.githubusercontent.com/95114594/145011902-34ab8f46-27cb-446d-ad87-1d2ebc110c23.jpg)
![teacher](https://user-images.githubusercontent.com/95114594/145011969-a34bba3d-b8f0-4b12-80bd-522c990818f9.jpg)
![parent](https://user-images.githubusercontent.com/95114594/145011978-efd89456-f170-4033-a2b7-42604ac085b7.jpg)
![user](https://user-images.githubusercontent.com/95114594/145011981-d2967007-e027-4647-a90a-ca55b0eb9ffc.jpg)

**Comment by sachinraj07** [comment]
Check the screenshots

**Comment by yungifez** [comment]
​            ​@if​(​Qs​::​userIsTeamSA​()​) 
 ​                <​div​ ​class​=​"​card​"​> 
 ​                    <​div​ ​class​=​"​card-header header-elements-inline​"​> 
 ​                        <​h6​ ​class​=​"​font-weight-bold​"​>​{{​ ​$ex​->​name​.​'​ - ​'​.​$ex​->​year​ ​}​}​</​h6​> 
 ​                        ​{!!​ Qs​::​getPanelOptions​() ​!​!} 
 ​                    </​div​> 
  
 ​                    <​div​ ​class​=​"​card-body collapse​"​> 
  
 ​                        ​{{--​Sheet Table​--}} 
 ​                        ​@include​(​'​pages.support_team.marks.show.sheet​'​) 
  
 ​                        ​{{--​Print Button​--}} 
 ​                        <​div​ ​class​=​"​text-center mt-3​"​> 
 ​                            <​a​ ​target​=​"​_blank​"​ ​href​=​"​{{​ ​route​(​'​marks.print​'​, [Qs​::​hash​(​$student_id​), ​$ex​->​id​, ​$year​]) ​}​}​"​ ​class​=​"​btn btn-secondary btn-lg​"​>Print Marksheet <​i​ ​class​=​"​icon-printer ml-2​"​></​i​></​a​> 
 ​                        </​div​> 
  
 ​                    </​div​> 
  
 ​                </​div​> 
 ​        ​@endif

As I can see here there was an if statement check for super admin 

Im not sure how the creator intended this to be 

But if you do want everyone to be able to view it, remove the if statement

**Comment by sachinraj07** [comment]
where is this?

**Comment by yungifez** [comment]
It's located in resources/pages/support_team/marks/show/index.blade.php I think 

From line 14 to maybe 31c

**Comment by sachinraj07** [comment]
ok, let me check

**Comment by sachinraj07** [comment]
Thanks it is working. I think creator wants to hide "AFFECTIVE TRAITS" and "PSYCHOMOTOR SKILLS" for students, parents and teachersbut he placed  if statement check in wrong place.

**Comment by yungifez** [comment]
I remember seeing an issue in that page but I forgot about it 

Can you please post a screenshot of the exam comments tab opened for all users

**Comment by sachinraj07** [comment]
exam comments does not show when login as student and parent,
Login As a teacher show only one  "Teacher's Comment"
Login as SuperAdmin shows two "Teacher's Comment and "Head Teacher's Comment"

**Comment by sachinraj07** [comment]
still you need screenshots?

**Comment by yungifez** [comment]
Yes it would be appreciated

**Comment by sachinraj07** [comment]
![admin](https://user-images.githubusercontent.com/95114594/145018079-225c57f5-b67e-4cac-899f-2890a2905a15.jpg)
![student](https://user-images.githubusercontent.com/95114594/145018101-9545eff4-3f0f-40a1-8156-7382dca8b0c0.jpg)
![teacher](https://user-images.githubusercontent.com/95114594/145018106-9e54eb12-2a6c-4555-94ab-b5a6fd60060c.jpg)
![parent](https://user-images.githubusercontent.com/95114594/145018109-b085e16d-fa6b-4427-b050-e3d917a55f26.jpg)

**Comment by sachinraj07** [comment]
"Please improve" is written by me in user teacher

**Comment by yungifez** [comment]
Ok 

Everything works fine so the issue can be closed
