### ISSUE TITLE
Not a Issue Its sugestion

### ISSUE THREAD

**Issue by baberansari** [4jean/lav_sms#41]
Kindly Add student fees table and create student fee table store student id 
or student id k against fees store ho or one table for expance create expance jaha per school k expance amount store ho ga is k sath sath reports student fee collection report total expance report.total fee collection se expance minus karn  profit report 
expance head 
teacher selary
mentance
tea
inshallallah i will work on it after compelete work i will push the code

**Comment by 4jean** [comment]
Your request is too specific or broad, please work with a dev to help meet your needs
