### ISSUE TITLE
Create/Update Student error

### ISSUE THREAD

**Issue by ritechoice23** [4jean/lav_sms#42]
**500 Internal Server Error Please Check for Duplicate entry or Contact School Administrator/IT Personnel**

I always get the above error any time I update a student or create a new one

**Comment by yungifez** [comment]
Does this happen all the time

**Comment by yungifez** [comment]
First of all make sure your .env file has

APP_DEBUG true ( do this in local dev )

Go to resources/views/pages/support_team/students/add.blade.php look for 
<form id="ajax-reg" method="post" ...........

Remove the ajax-reg so it would look like

<form id="" method="post"........

Try creating a student, then screenshot the error and post here

**Comment by ritechoice23** [comment]
i have done that but not getting any error, but I noticed the error always show if user image is added

**Comment by yungifez** [comment]
Have you modified the code in any way?

**Comment by 4jean** [comment]
As @yungifez  suggested
turn on app debug in .env, 
remove ajax-update class in https://github.com/4jean/lav_sms/blob/master/resources/views/pages/support_team/students/edit.blade.php (Line 12) 
remove ajax-reg id in https://github.com/4jean/lav_sms/blob/master/resources/views/pages/support_team/students/add.blade.php (Line 11)
Try the add and update actions and share screenshot of error, it could be a possible violation of unique column constraint in db
