### ISSUE TITLE
help

### ISSUE THREAD

**Issue by PavanKumar-18** [4jean/lav_sms#43]
i did alll but still showing php artisan queue:restart after running php artisan key:generate
Illuminate\Encryption\MissingAppKeyException
No application encryption key has been specified.

**Comment by yungifez** [comment]
Check your .env file

See if app key is set

**Comment by yungifez** [comment]
Can you post what you tried running and the errors you got

**Comment by PavanKumar-18** [comment]
D:\xampp\htdocs\lav_sms-master\
Illuminate\Encryption\MissingAppKeyException
No application encryption key has been specified.
http://127.0.0.1:8000/

**Comment by PavanKumar-18** [comment]
Illuminate\Encryption\EncryptionServiceProvider::Illuminate\Encryption\{closure}
D:\xampp\htdocs\lav_sms-master\vendor\laravel\framework\src\Illuminate\Encryption\EncryptionServiceProvider.php:101

**Comment by yungifez** [comment]
Please run this query 

Php artisan config:clear

**Comment by PavanKumar-18** [comment]
I
 did it earlier its doing same

**Comment by yungifez** [comment]
Try doing it again 

Because your configuration is most likely cached

**Comment by PavanKumar-18** [comment]
yes your right this time i did delete and create again  (.env) file .I followed your method now login page opened. thanks

**Comment by yungifez** [comment]
You are truly welcome

**Comment by PavanKumar-18** [comment]
GET http://localhost/global_assets/images/user.png 404 (Not Found) in register page iam getting  same where i go to solove

**Comment by yungifez** [comment]
Try running php artisan storage:link

**Comment by PavanKumar-18** [comment]
![image](https://user-images.githubusercontent.com/99017265/157016480-3149f7b3-3d02-40e1-b063-a78326e51034.png)

**Comment by PavanKumar-18** [comment]
![image](https://user-images.githubusercontent.com/99017265/157017048-9d3e00d3-5aa8-4cc9-9d4a-c32d608aabdd.png)
in register page

**Comment by yungifez** [comment]
Your url seems to not match your .env 

I notice you are running this in a local environment most probably xampp 

Use the built in laravel server

Close down xampp and run

Php artisan serve 

Then copy the given url and test the app like that

**Comment by PavanKumar-18** [comment]
![image](https://user-images.githubusercontent.com/99017265/157017937-1227495e-3c5d-473e-8240-9ad2297609d4.png)

**Comment by PavanKumar-18** [comment]
both doing same error

**Comment by yungifez** [comment]
Go to your .env and change 

APP_URL to 

http://localhost:8000

**Comment by PavanKumar-18** [comment]
GET http://127.0.0.1:8000/js/app.js net::ERR_ABORTED 404 (Not Found)

**Comment by PavanKumar-18** [comment]
APP_NAME=Laravel
APP_ENV=local
APP_KEY=base64:wjUzQlENU5Bb04kN3ZqhVndcaBZswK3xXj+BHPXmVEk=
APP_DEBUG=true
APP_URL=http://localhost:8000

LOG_CHANNEL=stack

DB_CONNECTION=mysql
DB_HOST=127.0.0.1
DB_PORT=3306
DB_DATABASE=SMS
DB_USERNAME=root
DB_PASSWORD=

BROADCAST_DRIVER=log
CACHE_DRIVER=file
QUEUE_CONNECTION=sync
SESSION_DRIVER=file
SESSION_LIFETIME=120

REDIS_HOST=127.0.0.1
REDIS_PASSWORD=null
REDIS_PORT=6379

MAIL_DRIVER=smtp
MAIL_HOST=smtp.mailtrap.io
MAIL_PORT=2525
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ENCRYPTION=null

PUSHER_APP_ID=
PUSHER_APP_KEY=
PUSHER_APP_SECRET=
PUSHER_APP_CLUSTER=mt1

MIX_PUSHER_APP_KEY="${PUSHER_APP_KEY}"
MIX_PUSHER_APP_CLUSTER="${PUSHER_APP_CLUSTER}"

**Comment by PavanKumar-18** [comment]
still  facing same problem

**Comment by yungifez** [comment]
Hmmmm send a screenshot
