### ISSUE TITLE
register error

### ISSUE THREAD

**Issue by PavanKumar-18** [4jean/lav_sms#44]
Illuminate\Database\QueryException
SQLSTATE[HY000]: General error: 1364 Field 'code' doesn't have a default value (SQL: insert into `users` (`name`, `email`, `password`, `updated_at`, `created_at`) values (Pavan, pavan@gmail.com, $2y$10$NJUlKDjkp5m5L731Oh84v.CPabN.o81reJ1aUt5SIcPoJvchf5YuC, 2022-03-07 11:55:00, 2022-03-07 11:55:00))

**Comment by yungifez** [comment]
What did you try doing

**Comment by PavanKumar-18** [comment]
i just try add new profile so register its shows that error

**Comment by yungifez** [comment]
Are you on WhatsApp 

Let me see if I can help you from there

**Comment by PavanKumar-18** [comment]
iam in office no phone allowed +919177052656 after 2hr

**Comment by yungifez** [comment]
Hmmm ok

**Comment by PavanKumar-18** [comment]
thanks pls help same error happen my few other projects to.

**Comment by PavanKumar-18** [comment]
wich verson node js need
