### ISSUE TITLE
How to get in touch regarding a security concern

### ISSUE THREAD

**Issue by JamieSlome** [4jean/lav_sms#47]
Hey there!

I belong to an open source security research community, and a member (@nightfury99) has found an issue, but doesn’t know the best way to disclose it.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by 4jean** [comment]
Thanks for your concern @JamieSlome Readme.md updated with contact for vulnerability report

**Comment by JamieSlome** [comment]
Thanks, @4jean 👍 I have also created #48.

In the meantime, you can view the report details [here](https://huntr.dev/bounties/b15177a8-5f6a-4227-91f8-a0e5ddf0b893/). It is private and only accessible to you.

Let me know if you have any questions or need support!

**Comment by 4jean** [comment]
Thanks for your response @JamieSlome , Issue should be resolved at 6c6d138837f2bdd450430eb8d85084ecf3f5a150

**Comment by JamieSlome** [comment]
@4jean - great, thank you for your time! Are you able to resolve the report?

**Comment by 4jean** [comment]
@JamieSlome it's been resolved. The commit fixed the issue

**Comment by 4jean** [comment]
You can make the issue on huntr as fixed

**Comment by JamieSlome** [comment]
@4jean - can you do so via the controls?

<a href="https://huntr.dev/bounties/b15177a8-5f6a-4227-91f8-a0e5ddf0b893/">
<img width="431" alt="Screenshot 2022-04-21 at 07 15 48" src="https://user-images.githubusercontent.com/55323451/164386562-11d4251a-ad3b-435b-8bb6-e1dd50dfeec2.png"></a>
